### ISSUE TITLE
Error converting month to number

### ISSUE THREAD

**Issue by palladionIT** [sourcethemes/academic-admin#1]
Hello,
I was just about to write my own script because I could not find one before. I am happy that you did the work now so everyone can use this awesome script.

I found a small bug that at least for me prevents the script from running. It exits with the following error:
`Traceback (most recent call last):                                                                                            
  File "/home/palladion/.local/lib/python3.6/site-packages/academic/cli.py", line 187, in month2number                        
    return str(list(calendar.month_abbr).index(month_abbr)).zfill(2)                                                          
ValueError: 'mar' is not in list`

At least in my locale _calendar.month_abbr_ gives me "Mar" instead of the expected lowercase "mar". Then the month can not be found in the list and the exception gets thrown.

I hope this helps. Thank you

**Comment by gcushen** [comment]
Thanks for reporting this!

Fixed in 460c057 .
