### ISSUE TITLE
import assets: download fonts too

### ISSUE THREAD

**Issue by gcushen** [sourcethemes/academic-admin#14]
- [ ] Add FA fonts
- [ ] Add Academicons fonts

**Comment by danielschemmel** [comment]
Considering that I just tackled this problem manually, I would like to offer taking this on.

Currently the directory structure looks like this:
```
static
├── css
│   ├── fonts
│   │   ├── academicons.eot
│   │   ├── ...
│   │   └── academicons.woff
│   ├── vendor
│   │   └── main.min.css
│   └── webfonts
│       ├── fa-brands-400.eot
│       ├── ...
│       └── fa-solid-900.woff2
└── js
    └── vendor
        └── main.min.js
```

I would like to propose putting `vendor` as the root folder, which would enable me to generate the following folder structure without rewriting the fontawesome or academicons css, as well as make for simple cleanup of the downloaded assets:
```
static
└── vendor
    ├── css
    │   └── main.min.css
    ├── fonts
    │   ├── academicons.eot
    │   ├── ...
    │   └── academicons.woff
    ├── js
    │   └── main.min.js
    └── webfonts
        ├── fa-brands-400.eot
        ├── ...
        └── fa-solid-900.woff2
```
The only drawback is that this would require changes to [the theme](https://github.com/gcushen/hugo-academic/blob/c5b26892a9c6edd861c86993fce1c4cc234b9408/layouts/partials/site_head.html#L59).

**Comment by gcushen** [comment]
Since this issue was originally opened, Academic has evolved to using the industry standard Node JS approach to downloading offline assets - see comment at https://github.com/gcushen/hugo-academic/pull/1554#issuecomment-596151573 .

Hence, please consider opening a PR on the Academic repo to improve handling of offline assets in https://github.com/gcushen/hugo-academic/blob/master/package.json and https://github.com/gcushen/hugo-academic/blob/master/scripts/update_bootstrap.sh . At the time of writing, Bootstrap and the [speaker notes tool](https://github.com/gcushen/hugo-academic/tree/master/static/js/vendor/reveal.js/plugin/notes) are the built-in offline assets.

As a result, our early Python-based approach to downloading assets will likely be deprecated once offline support has migrated to the Node JS approach.
