### ISSUE TITLE
import assets: include MathJax & Reveal extensions

### ISSUE THREAD

**Issue by gcushen** [sourcethemes/academic-admin#15]
Problem, as defined in #13:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (MathMenu.js, line 0)
[Error] Refused to execute http://localhost:1313/extensions/MathMenu.js?V=2.7.4 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (MathZoom.js, line 0)
[Error] Refused to execute http://localhost:1313/extensions/MathZoom.js?V=2.7.4 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
```

Similar situation with other dynamically loaded scripts such as Reveal extensions.

**Comment by danielschemmel** [comment]
I have successfully (manually) gotten mathjax to work by dumping [all the additional mathjax scripts](https://github.com/mathjax/MathJax) in `/static/js/vendor`. Note that MathJax is loaded unconditionally that way due too the inclusion of its core script in `/static/js/vendor/main.min.js` - a fix for that would require a slight modification to `site_head.html` in the template.

**Comment by gcushen** [comment]
Since this issue was originally opened, Academic has evolved to using the industry standard Node JS approach to downloading offline assets - see comment at https://github.com/gcushen/hugo-academic/pull/1554#issuecomment-596151573 .

Hence, please consider opening a PR on the Academic repo to improve handling of offline assets in https://github.com/gcushen/hugo-academic/blob/master/package.json and https://github.com/gcushen/hugo-academic/blob/master/scripts/update_bootstrap.sh . At the time of writing, Bootstrap and the [speaker notes tool](https://github.com/gcushen/hugo-academic/tree/master/static/js/vendor/reveal.js/plugin/notes) are the only built-in offline assets.

As a result, our early Python-based approach to downloading assets will likely be deprecated once offline support has migrated to the Node JS approach.
