### ISSUE TITLE
Incorrect parsing of unquoted months

### ISSUE THREAD

**Issue by gustybear** [sourcethemes/academic-admin#23]
The unquoted months field in the bibtex cause a crash.
`
@article{ZhengLocationBasedHandshake2017,
  title = {Location {{Based Handshake}} and {{Private Proximity Test}} with {{Location Tags}}},
  volume = {14},
  copyright = {All rights reserved},
  number = {4},
  journal = {IEEE Transactions on Dependable and Secure Computing},
  author = {Zheng, Yao and Li, Ming and Lou, Wenjing and Hou, Y. Thomas},
  month = jul,
  year = {2017},
  keywords = {journal},
  pages = {406--419},
  file = {/Users/yao/Cloud/Zotero/storage/ZD5TTQHE/Zheng et al. - 2017 - Location Based Handshake and Private Proximity Tes.pdf}
}
`
It causes
`
bibtexparser.bibdatabase.UndefinedString: 'jul'
`

It has an easy fix. Replace
`
parser = BibTexParser()
`
with
`
parser = BibTexParser(common_strings=True)
`

**Comment by gcushen** [comment]
It appears that by itself, that Bibtex entry is invalid since it refers to an undefined month variable.

However, thanks for proposing a solution so that we can add robustness to the Bibtex entries that the tool is able to parse.

I'll commit the improvement shortly :)

**Comment by gcushen** [comment]
Just added support for externally defined months in  51d56b9 . v0.2.8 is now available on Pypi.

**Comment by gustybear** [comment]
Thanks. This is a very good project. My students love the interface.
http://www2.hawaii.edu/~yaozheng/
