### ISSUE TITLE
import --bibtex creates strange filenames for *.bib files

### ISSUE THREAD

**Issue by andreas-h** [sourcethemes/academic-admin#29]
I just installed using `pip install academic`; `academic -h` tells me I'm using version v0.3.0.

When I run `academic import --normalize --bibtex publications.bib`, the `*.bib` files which are created all have the filename `{slugify(entry['ID'])}.bib`.  In my site, when clicking on the *download* link in the *cite* popup, I do get prompted for the download, and the download works okay, but the filename is again `{slugify(entry['ID'])}.bib`, which is ugly and confusing.

**Comment by andreas-h** [comment]
Just noticed that in the *cite* popup, there is the message *Error: 0 error* written in red next to the *download* button, but the download still works.

**Comment by gcushen** [comment]
There is only one form of ID available to us per Bibtex entry. The folder name created by this tool is the Bibtex ID which many reference managers give you the freedom to define. The rest of the algo is just converting it to a web-safe name. I have opened #30 to propose our own ID generation scheme - feel free to contribute.

**Comment by andreas-h** [comment]
Thanks for the quick reply. However, it seems there's a misunderstanding.  The filename of the generated `*.bib` files is *literally* `{slugify(entry['ID'])}.bib`, even though in my source BibTeX file, I have IDs like 

    @Article{hilboll_long-term_2013,

and so on.  Is this really the expected behavior?
