### ISSUE TITLE
Support custom publication types

### ISSUE THREAD

**Issue by vitorenesduarte** [sourcethemes/academic-admin#3]
Hi. How are you inteding to deal with https://github.com/sourcethemes/academic-admin/blob/master/academic/cli.py#L115?
I can try to help!

**Comment by gcushen** [comment]
The publication types have been implemented and just pushed to GitHub and new version released :)

There is still lots of room for improvements, such as with generating the TOML for `publication`.

**Comment by vitorenesduarte** [comment]
Would it make sense to be able to overwrite this behaviour by having, for example, some tag with the publication type in the bibtex?
I have a custom publication type "workshop paper", which cannot be distinguish by checking the `ENTRYTYPE`.

**Comment by gcushen** [comment]
For custom types, we could consider something like you suggested. For example supporting an optional key-value pair, where `academic_item_type` is the key, to the BibTeX `notes` field (appears in Zotero as *Extras*).

It would be good to get more feedback on this...

**Comment by gcushen** [comment]
Closing this as the issue has gone stale without any contributions. Feel free to contribute a PR that implements your proposal.
