### ISSUE TITLE
Local assets do not seem to be considered

### ISSUE THREAD

**Issue by Victor-Morel** [sourcethemes/academic-admin#34]
Hello,
I'm delighted to find out there is a possibility to use the academic theme without having to give away the privacy of my visitors.  
However, after installing academic-admin and running `academic import --assets`, my extension Privacy Badger tells me there still are trackers on my website.  
What could have gone wrong?
Thanks

**Comment by gcushen** [comment]
Depending on which features (and thus assets) you are using, your specific set of attributes may not be fully downloaded as the community has not completed the implemention of this tool for all assets. Please refer to the open issues and consider contributing.
