### ISSUE TITLE
Add support for Biber - different date format

### ISSUE THREAD

**Issue by ChasNelson1990** [sourcethemes/academic-admin#40]
Hi,

Recently started using HUGO and the academic theme, so far so good!

However, I've hit a mini-hurdle when trying to use your script to convert a .bib to many .bibs for my publications record.

Essentially, I use biblatex. It seems the only really problem this causes is parsing months. In biblatex months are already a 2-digit number, .e.g 04 not apr.

Would it be worth adding an extra level of robustness to your python script to parse numeric months?

I've made the changes to my fork and will create a pull request referencing this issue for you to decide on.

Thanks,

Chas

**Comment by gcushen** [comment]
See #32
