### ISSUE TITLE
Italics are stripped from titles

### ISSUE THREAD

**Issue by zkamvar** [sourcethemes/academic-admin#43]
I have a bibtex entry from [my bibtex repository](https://github.com/zkamvar/znk-bibliography) that looks like this:

```latex
@article{kamvar2018something,
  title = {Something in the agar does not compute: on the discriminatory power of mycelial compatibility in {\textit{Sclerotinia sclerotiorum}}},
  volume = {44},
  issn = {1983-2052},
  url = {https://doi.org/10.1007/s40858-018-0263-8},
  doi = {10.1007/s40858-018-0263-8},
  number = {1},
  journal = {Tropical Plant Pathology},
  publisher = {Springer Science and Business Media LLC},
  author = {Kamvar, Zhian N. and Everhart, Sydney E.},
  year = {2018},
  month = {Nov},
  pages = {32–40}
} 
```

However, when I try to import it with academic, the curly braces get stripped away and the species name goes from *Sclerotinia sclerotiorum* to \textitSclerotinia sclerotiorum:

```latex
@article{kamvar2018something,
 author = {Kamvar, Zhian N. and Everhart, Sydney E.},
 doi = {10.1007/s40858-018-0263-8},
 issn = {1983-2052},
 journal = {Tropical Plant Pathology},
 month = {Nov},
 number = {1},
 pages = {32–40},
 publisher = {Springer Science and Business Media LLC},
 title = {Something in the agar does not compute: on the discriminatory power of mycelial compatibility in \textitSclerotinia sclerotiorum},
 url = {https://doi.org/10.1007/s40858-018-0263-8},
 volume = {44},
 year = {2018}
}
```

Is there a way to get the bibtex parser to replace common tags like textit, textbf, and textsc with their html equivalents?

**Comment by gcushen** [comment]
The HTML title tag and Academic do not support formatting of titles. All titles must currently be plain text. Feel free to investigate is Bibtex Parser has an option for this or contribute an improvement to strip any latex tags from titles when importing publications.
