### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by srossi93** [sourcethemes/academic-admin#52]
Hi, first of all thank you for this incredible template and these scripts.

I would suggest to push a new release on pip -- current one has some broken issues with publications. 
For example, the cite button does not work.
Latest release available saves the bib with the full cite key, while academic expect only `cite.bib`.
The code on the [master](https://github.com/sourcethemes/academic-admin/blob/a6467c9f1b36bc129271fbe074d7475e86bdca49/academic/cli.py#L120) fixed it but its not available on PyPI.
#### Example
```
Parsing entry Author2019
Creating folder content/publication/author-2019
Saving citation to content/publication/author-2019/author-2019.bib
Saving Markdown to 'content/publication/author-2019/index.md'
```

Can you create a new release?

**Comment by gcushen** [comment]
Done: https://github.com/sourcethemes/academic-admin/releases/tag/0.5.0
