### ISSUE TITLE
Add logger and verbose mode

### ISSUE THREAD

**Issue by gcushen** [sourcethemes/academic-admin#6]
- [ ] Add Python's logger for proper logging.
- [ ] Convert all or most `print` statements to appropriate level (e.g. Info) logging statements
- [ ] Add `-v` and `--verbose` arguments for verbose mode.
- [ ] Only output info type messages in verbose mode

**Comment by Cyber4Food** [comment]
Please merge my PR to fix the first bullet point of your list.

thanks :)

**Comment by FramboisePi** [comment]
Hello,
I will try to do this...
I just have one question. What does the last point means?
Does it means in verbose mode we need to output every messages including info type messages?
Or does it mean in verbose mode we must output info type messages only?
Sorry if the question seems stupid but I was not sure about this element.

**Comment by gcushen** [comment]
The Verbose mode would display log messages up to Info level (i.e. not display any Debug level messages). More info in the official Python3 logging docs and here: https://docs.python.org/3/library/logging.html

**Comment by FramboisePi** [comment]
Oh 🤭, I forgot there were a Debug Mode. Thank you for your answer. 
I went to the second link, it seems it's an interressant website.
I will try to make a first pull request. Thank you for your help.
