### ISSUE TITLE
Import --assets is incomplete

### ISSUE THREAD

**Issue by klein-j** [sourcethemes/academic-admin#63]
I am trying to build a static site, that is truly independent from external resources. From the descriptions it sounds like this tool is intended to exactly do this.

However after downloading the css files, the website still downloads fonts from gstatic.com, and it still connects to identity.netlify.com (however this might be due to another reason, I guess). Also I got the issue that after performing the command all icons (presumably from font-awesome) stop working.

Therefore I think it would be good to clearly state the purpose of this tool in the documentation and what it does and what not. Better yet, it would be awesome if it actually would download all external dependencies and build a self-sustained site.

**Comment by gcushen** [comment]
The font theme defines which fonts you use and Netlify Identity can be disabled in `params.toml`.

This tool is focussed on importing Bibtex publications.

We now use the standard NPM approach for importing assets for offline use and there is an opportunity to extend it beyond Bootstrap for admins who don't wish to use third party CDNs. See https://github.com/sourcethemes/academic-admin/issues/14#issuecomment-605617261

**Comment by gcushen** [comment]
Feel free to add your support to https://github.com/gcushen/hugo-academic/issues/1167 and consider contributing
