### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by benoit-sbr** [sourcethemes/academic-admin#8]
Hi,

First, thumbs up for what looks like a great tool. Unfortunately I didn't succeed in the installation. I have python3 setup, I did `pip3 install -U academic` with success, but trying to import returns the following `academic: command not found`

Sorry to bother you with probably a trivial question, but what did I do wrong (Academic was installed with git, hugo is installed version v0.50)?

**Comment by gcushen** [comment]
Check which environment it was installed into - ideally it should be installed in the global environment rather than a virtual environment. Otherwise, your environment may need reloading to pick up the new installation - see similar questions on StackExchange.

**Comment by benoit-sbr** [comment]
Hi gcushen,
After a reboot it's working fine. Thanks for the clue, I will try to learn deeper about environments.
First import went well. Now I will test different use cases and report if need be.

Feel free to remove the issue!

**Comment by LeoBman** [comment]
For anyone struggling to pip install into global environment, this worked for me:

sudo -H pip3 install -U academic

see https://stackoverflow.com/questions/36936212/how-do-i-install-a-pip-package-globally-instead-of-locally
